# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [13]:
import numpy as np
 

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [14]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)
print("dimension (ndim):", A. ndim)
print("shape:", A.shape)
print("size:", A.size)
print("datatype:", A.dtype)


dimension (ndim): 2
shape: (3, 5)
size: 15
datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2


print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [21]:
import numpy as np
B = np.arange(1,10).reshape(3,3)
C = np.ones((3,3))*2
print(B)
print()
print(C)

# Elementwise_subtration
elementwise_sub = B-C
print(elementwise_sub)

# Elementwise_multiplication
elementwise_mul = B*C
print(elementwise_mul)

# Matrix multiplication 
matrix_mul = B@C
print(matrix_mul)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [22]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
import numpy as np
D = np.arange(1,10).reshape(3,3)
print(D)
# 1 Exponentiate each number elementwise(use the np.exp function.)
D_exp = np.exp (D)
print("1. matris (e^x barje element):")
print(D_exp)

# 2 Calculate the minimum value in the whole matrix.
min_whole = np.min(D)
print({min_whole})

# 3 Calculate the minum value in each row.
min_rows = np.min (D, axis=1)
print(min_rows)

# 4 Calculate the minum value in each column.
min_cols = np.min (D, axis=0)
print(min_cols)

# 5 Find the index value for the minimun value in the whole matrix (hint:use np.argmin.)
min_index_whole = np.argmin(D)
print(f"5. Indexför minsta värdei hela matrisen (platt index):{min_index_whole}")
print(" (rad, kolumn) = (0,0) för värde 1")
print()

# 6 Find the index value for the minimun value in each row (hint: use np. argmin.)
min_indices_row = np.argmin(D, axis=1)
print(min_indices_row)

# 7 Calculate the sum for all elements.
sum_all = np.sum(D)
print(sum_all)

# 8 Calculate the mean for each column.
mean_cols = np.mean(D, axis=0)
print(mean_cols)

# 9 Calculate the median for each column.
median_cols = np.median(D, axis=0)
print(median_cols)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
1. matris (e^x barje element):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
{np.int64(1)}
[1 4 7]
[1 2 3]
5. Indexför minsta värdei hela matrisen (platt index):0
 (rad, kolumn) = (0,0) för värde 1

[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
# När man segementerar en array i flera dimentioner, och färre index anges än antalet axalar,
# betraktas de saknade indexen som kompletta segment. Darför, när man i huvudsak gör det när man 
# anropar x[:] är x[:,:][1,:]. Därför kommer x[:,:] bara att returnera x själv. 



### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [ ]:
# För att iterera elementvis i en multidimensionell array behöver man-
# använda numpy-funtioner som nditer(), flat eller flatten() beroende på strukturen.

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [34]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#Koden skapar en 3D-array b från en 1D-array a och tre axlar betyder att arrayen har 
# tre dimentsioner :(2,3,5).


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [35]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [36]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [37]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [57]:
import numpy as np

def add_mult_matrices(A, B, operation):
    # kontrollera att båda är numpy-arrays
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
        raise TypeError("Inputs must be numpy arrays")

    # kontrollera operation
    if operation not in ["add", "multiply"]:
        raise ValueError("Operation must be 'add' or 'multiply'")

    if operation == "add":
        if A.shape != B.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return A + B

    if operation == "multiply":
        if A.shape[1] != B.shape[0]:
            raise ValueError("Matrix sizes do not conform for multiplication")
        return A @ B





A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

# addition 
print (add_mult_matrices(A, B, "add"))

# Multiplikation 
print (add_mult_matrices (A, B, "multiply"))


[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [3]:
import numpy as np
x = np.array([[4,3]]) #shape:(1, 2) - 1 rad, 2 kolumner 
print(f"x = {x}")
print(f"shape/ dimension {x.shape}{x.shape[0]} rad, {x.shape[1]}kolumner")


#(a)Vilken dimension har vektor X?
x = np.array ([[4, 3]])
print(f"x = {x}")
print(f"Shape/dimension: {x.shape}{x .shape[0]}rad, {x. shape[1]} kolumner")


print("\n" + "="*70)
print("(b)-(f)Skalär multiplikation och addition") 
print("="*70)

#(b) Beräkna 5x 

print (f"(b) 5x = 5 x {x} = {5 * x})")


#(c) Beräkna 3x.
print (f"(c) 3x = 3 x {x} = {3 * x }")


#(d) Beräkna 5x +3x
print (f"(d) 5x + 3x {5*x} {3*x} = 5*x + 3*x")
print (f" Alternativ: (5+3)x = 8 x = {8*x}")


#(e) Beräkna 8x
print (f"(e) 8x = {8*x}")


#(f) Beräkna 4x - x
print (f"(f) 4x - x = {4*x} - {x} = {4*x - x }")
print (f" Alternativt: (4-1)x = 3x ={3*x}")




print("\n" + "="*70)
print("(g) Transponering: x^T") 
print("="*70)


#(g) Beräkna xT , vilken blir den nya dimensionen efter att tansponeringen utförs?

x_transpose = x.T  
print(f"x = {x} (dimension: {x.shape})")
print(f"x^T = {x_transpose} (dimension: {x_transpose.shape})")
print(f"Svar: Den nya dimensionen är {x_transpose.shape},  {x_transpose.shape[0]} ×{x_transpose.shape[1]}")


#(h) Är x + xT definerat?
print("\n" + "="*70)
print("(h) Är x + x^T definierat?")
print("="*70)
print(f"x har dimension: {x.shape}")
print(f"x^T har dimension: {x_transpose.shape}")
print("\nEnligt linjär algebra:")
print("- För matrisaddition måste båda matriserna ha SAMMA dimensioner.")
print(f"- x är {x.shape[0]}×{x.shape[1]}, x^T är {x_transpose.shape[0]}×{x_transpose.shape[1]}")
print("- Dessa är inte lika, så operationen är INTE definierad enligt strikta matrisregler.")
print("\nSvar är: NEJ, x + x^T är inte definierat enligt linjär algebra.")



#(i) Beräkna ||x||.
print("\n" + "="*70)
print("(i) Beräkna ||x|| (normen/längden av x)")
print("="*70)

# För en vektor [a, b] är normen/längden: sqrt(a² + b²)
norm_x = np.linalg.norm(x)
print(f"x = {x}")
print(f"||x|| = sqrt({x[0,0]}² + {x[0,1]}²) = sqrt({x[0,0]**2} + {x[0,1]**2})")
print(f"       = sqrt({x[0,0]**2 + x[0,1]**2}) = {norm_x}")
print(f"Svar: ||x|| = {norm_x:.2f}")

# Kontroll med Pythagoras sats:
print(f"\nKontroll: 4² + 3² = 16 + 9 = 25, sqrt(25) = 5")
print(f"Svar: ||(4,3)|| = 5")

x = [[4 3]]
shape/ dimension (1, 2)1 rad, 2kolumner
x = [[4 3]]
Shape/dimension: (1, 2)1rad, 2 kolumner

(b)-(f)Skalär multiplikation och addition
(b) 5x = 5 x [[4 3]] = [[20 15]])
(c) 3x = 3 x [[4 3]] = [[12  9]]
(d) 5x + 3x [[20 15]] [[12  9]] = 5*x + 3*x
 Alternativ: (5+3)x = 8 x = [[32 24]]
(e) 8x = [[32 24]]
(f) 4x - x = [[16 12]] - [[4 3]] = [[12  9]]
 Alternativt: (4-1)x = 3x =[[12  9]]

(g) Transponering: x^T
x = [[4 3]] (dimension: (1, 2))
x^T = [[4]
 [3]] (dimension: (2, 1))
Svar: Den nya dimensionen är (2, 1),  2 ×1

(h) Är x + x^T definierat?
x har dimension: (1, 2)
x^T har dimension: (2, 1)

Enligt linjär algebra:
- För matrisaddition måste båda matriserna ha SAMMA dimensioner.
- x är 1×2, x^T är 2×1
- Dessa är inte lika, så operationen är INTE definierad enligt strikta matrisregler.

Svar är: NEJ, x + x^T är inte definierat enligt linjär algebra.

(i) Beräkna ||x|| (normen/längden av x)
x = [[4 3]]
||x|| = sqrt(4² + 3²) = sqrt(16 + 9)
       = sqrt(25) = 5.0
Svar: ||x|| =

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [6]:
# Övningsuppgifter 
# Definera matriserna 


import numpy as np

# -------------------------------------------------------
# DEFINERA MATRISERNA
# -------------------------------------------------------
A = np.array([[2, 1, -1], [1, -1, 1]])        # 2×3
B = np.array([[4, -2, 1], [2, -4, -2]])       # 2×3
C = np.array([[1, 2], [2, 1]])                # 2×2
D = np.array([[3, 4], [4, 3]])                # 2×2
E = np.array([[1], [2]])                      # 2×1 (kolumnvektor)
I = np.array([[1, 0], [0, 1]])                # 2×2 (identitetsmatris)

print("Definierade matriser:")
print(f"A (2×3) = \n{A}")
print(f"\nB (2×3) = \n{B}")
print(f"\nC (2×2) = \n{C}")
print(f"\nD (2×2) = \n{D}")
print(f"\nE (2×1) = \n{E}")
print(f"\nI (2×2) = \n{I}")

# -------------------------------------------------------
# (a) 2A
# -------------------------------------------------------
print("\n" + "="*60)
print("(a) 2A")
print("="*60)
result = 2 * A
print(f"2A = 2 × \n{A} = \n{result}")

# -------------------------------------------------------
# (b) B - 2A
# -------------------------------------------------------
print("\n" + "="*60)
print("(b) B - 2A")
print("="*60)
if A.shape == B.shape:
    result = B - (2 * A)
    print(f"B - 2A = \n{B} - \n{2*A} = \n{result}")
else:
    print("Ej definierad: A och B har olika dimensioner")

# -------------------------------------------------------
# (c) 3C - 2E
# -------------------------------------------------------
print("\n" + "="*60)
print("(c) 3C - 2E")
print("="*60)
# C är 2×2, E är 2×1 - dessa har olika dimensioner
# 3C är 2×2, 2E är 2×1, subtraktion kräver samma dimensioner
print("Ej definierad: C (2×2) och E (2×1) har olika dimensioner")

# ---------------------------------------------------------
# (d) 2D - 3C
# ---------------------------------------------------------
print("\n" + "="*60)
print("(d) 2D - 3C")
print("="*60)
if D.shape == C.shape:
    result = (2 * D) - (3 * C)
    print(f"2D - 3C = 2×\n{D} - 3×\n{C} = \n{result}")
else:
    print("Ej definierad: D och C har olika dimensioner")
    
# --------------------------------------------------------
# (e) D^T + 2D
# --------------------------------------------------------
print("\n" + "="*60)
print("(e) D^T + 2D")
print("="*60)
D_T = D.T
print(f"D^T = \n{D_T}")
print(f"2D = \n{2*D}")
if D_T.shape == D.shape:
    result = D_T + (2 * D)
    print(f"D^T + 2D = \n{result}")
else:
    print("Ej definierad: D^T och D har olika dimensioner")

# --------------------------------------------------------
# (f) 2C^T - 2D^T
# --------------------------------------------------------
print("\n" + "="*60)
print("(f) 2C^T - 2D^T")
print("="*60)
C_T = C.T
D_T = D.T
print(f"C^T = \n{C_T}")
print(f"D^T = \n{D_T}")
if C_T.shape == D_T.shape:
    result = (2 * C_T) - (2 * D_T)
    print(f"2C^T - 2D^T = \n{result}")
else:
    print("Ej definierad: C^T och D^T har olika dimensioner")

# -------------------------------------------------------
# (g) A^T - B
# -------------------------------------------------------
print("\n" + "="*60)
print("(g) A^T - B")
print("="*60)
A_T = A.T
print(f"A^T (3×2) = \n{A_T}")
print(f"B (2×3) = \n{B}")
print("Ej definierad: A^T är 3×2, B är 2×3 - olika dimensioner")

# -------------------------------------------------------
# (h) AC
# -------------------------------------------------------
print("\n" + "="*60)
print("(h) AC (A × C)")
print("="*60)
print(f"A (2×3) × C (2×2)")
print("För matrismultiplikation måste antalet kolumner i A vara lika med antalet rader i C")
print(f"Antal kolumner i A: {A.shape[1]}")
print(f"Antal rader i C: {C.shape[0]}")
if A.shape[1] == C.shape[0]:
    result = np.dot(A, C)
    print(f"AC = \n{result}")
else:
    print("Ej definierad: Antal kolumner i A (3) ≠ antal rader i C (2)")

# -------------------------------------------------------
# (i) CD
# -------------------------------------------------------
print("\n" + "="*60)
print("(i) CD (C × D)")
print("="*60)
if C.shape[1] == D.shape[0]:
    result = np.dot(C, D)
    print(f"CD = \n{result}")
else:
    print("Ej definierad")

# -----------------------------------------------------
# (j) CB
# -----------------------------------------------------
print("\n" + "="*60)
print("(j) CB (C × B)")
print("="*60)
print(f"C (2×2) × B (2×3)")
if C.shape[1] == B.shape[0]:
    result = np.dot(C, B)
    print(f"CB = \n{result}")
else:
    print("Ej definierad: Antal kolumner i C (2) ≠ antal rader i B (2)")

# ----------------------------------------------------
# (k) CI
# ---------------------------------------------------- 
print("\n" + "="*60)
print("(k) CI (C × I)")
print("="*60)
if C.shape[1] == I.shape[0]:
    result = np.dot(C, I)
    print(f"CI = C × I = \n{result}")
    print("OBS: C × I = C (eftersom I är identitetsmatrisen)")
else:
    print("Ej definierad")

# -----------------------------------------------------
# (l) AB^T
# -----------------------------------------------------
print("\n" + "="*70)
print("(l) AB^T (A × B^T)")
print("="*70)
B_T = B.T
print(f"B^T (3×2) = \n{B_T}")
print(f"A (2×3) × B^T (3×2)")
if A.shape[1] == B_T.shape[0]:
    result = np.dot(A, B_T)
    print(f"AB^T = \n{result}")
else:
    print("Ej definierad: Antal kolumner i A (3) ≠ antal rader i B^T (3)")

# --------------------------------------------------------------------
# SAMMANFATTNING AV ALLA RESULTAT
# --------------------------------------------------------------------
print("\n" + "="*60)
print("SAMMANFATTNING AV ALLA SVAR")
print("="*60)

summary = {
    "(a) 2A": "Definierad",
    "(b) B - 2A": "Definierad",
    "(c) 3C - 2E": "Ej definierad (olika dimensioner)",
    "(d) 2D - 3C": "Definierad",
    "(e) D^T + 2D": "Definierad",
    "(f) 2C^T - 2D^T": "Definierad",
    "(g) A^T - B": "Ej definierad (olika dimensioner)",
    "(h) AC": "Ej definierad (A:2×3, C:2×2 - inkompatibla)",
    "(i) CD": "Definierad",
    "(j) CB": "Definierad",
    "(k) CI": "Definierad (och = C)",
    "(l) AB^T": "Definierad"
}

for key, value in summary.items():
    print(f"{key}: {value}")



Definierade matriser:
A (2×3) = 
[[ 2  1 -1]
 [ 1 -1  1]]

B (2×3) = 
[[ 4 -2  1]
 [ 2 -4 -2]]

C (2×2) = 
[[1 2]
 [2 1]]

D (2×2) = 
[[3 4]
 [4 3]]

E (2×1) = 
[[1]
 [2]]

I (2×2) = 
[[1 0]
 [0 1]]

(a) 2A
2A = 2 × 
[[ 2  1 -1]
 [ 1 -1  1]] = 
[[ 4  2 -2]
 [ 2 -2  2]]

(b) B - 2A
B - 2A = 
[[ 4 -2  1]
 [ 2 -4 -2]] - 
[[ 4  2 -2]
 [ 2 -2  2]] = 
[[ 0 -4  3]
 [ 0 -2 -4]]

(c) 3C - 2E
Ej definierad: C (2×2) och E (2×1) har olika dimensioner

(d) 2D - 3C
2D - 3C = 2×
[[3 4]
 [4 3]] - 3×
[[1 2]
 [2 1]] = 
[[3 2]
 [2 3]]

(e) D^T + 2D
D^T = 
[[3 4]
 [4 3]]
2D = 
[[6 8]
 [8 6]]
D^T + 2D = 
[[ 9 12]
 [12  9]]

(f) 2C^T - 2D^T
C^T = 
[[1 2]
 [2 1]]
D^T = 
[[3 4]
 [4 3]]
2C^T - 2D^T = 
[[-4 -4]
 [-4 -4]]

(g) A^T - B
A^T (3×2) = 
[[ 2  1]
 [ 1 -1]
 [-1  1]]
B (2×3) = 
[[ 4 -2  1]
 [ 2 -4 -2]]
Ej definierad: A^T är 3×2, B är 2×3 - olika dimensioner

(h) AC (A × C)
A (2×3) × C (2×2)
För matrismultiplikation måste antalet kolumner i A vara lika med antalet rader i C
Antal kolumner i A: 3
Antal rad

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [76]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [7]:
import numpy as np

v1 = np.arange(4)
v2 = v1[-2:]

print(f"np.shares_memory(v1, v2): {np.shares_memory(v1, v2)}")  # True
print(f"v2.base is v1: {v2.base is v1}")  # True
print(f"v2.flags.owndata: {v2.flags.owndata}")  # False

np.shares_memory(v1, v2): True
v2.base is v1: True
v2.flags.owndata: False
